apiVersion: apps/v1
kind: Deployment
metadata:
  name: zoneprinter
  namespace: default
  labels:
    app: zoneprinter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zoneprinter
  template:
    metadata:
      labels:
        app: zoneprinter
    spec:
      containers:
      - name: frontend
        image: gcr.io/google-samples/zone-printer:0.1
        ports:
          - containerPort: 80
      affinity:                                                          
        podAntiAffinity:                                                 
          requiredDuringSchedulingIgnoredDuringExecution:                
          - labelSelector:                                             
              matchExpressions:                                        
              - key: app                                               
                operator: In 
                values:                                                
                - zoneprinter                                          
            topologyKey: failure-domain.beta.kubernetes.io/zone        
